<?php

namespace XvndBackendBundle\Repository;

/**
 * AdvertiserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertiserRepository extends \Doctrine\ORM\EntityRepository
{
}
