<?php

namespace XvndBackendBundle\Repository;

/**
 * CampaignTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
