<?php

namespace XvndBackendBundle\Repository;

/**
 * InputTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
