services:
    xvnd_backend.admin.advertiser:
        class: XvndBackendBundle\Admin\AdvertiserAdmin
        arguments: [~, XvndBackendBundle\Entity\Advertiser, XvndBackendBundle:AdvertiserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Advertiser, label: Alle anzeigen }
        public: true

    xvnd_backend.admin.campaign:
        class: XvndBackendBundle\Admin\CampaignAdmin
        arguments: [~, XvndBackendBundle\Entity\Campaign, XvndBackendBundle:CampaignAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Campaign, label: Alle anzeigen }
        public: true

    xvnd_backend.admin.publisher:
        class: XvndBackendBundle\Admin\PublisherAdmin
        arguments: [~, XvndBackendBundle\Entity\Publisher, XvndBackendBundle:PublisherAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Publisher, label: Alle anzeigen }
        public: true

    xvnd_backend.admin.placement:
        class: XvndBackendBundle\Admin\PlacementAdmin
        arguments: [~, XvndBackendBundle\Entity\Placement, XvndBackendBundle:PlacementAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Placement, label: Alle anzeigen }
        public: true
